### ISSUE TITLE
Who reviews the pull requests?

### ISSUE THREAD

**Issue by ingcrengifo** [ZennerIoT/ex_audit#47]
I have the pull request days ago https://github.com/ZennerIoT/ex_audit/pull/34 but nothing has happened.

**Comment by yukster** [comment]
I'm not an owner of this repo, but I think it would help get it reviewed if you added a test. There's a small example app in the repo (User, BlogPost, Comment) so you can make a test that uses insert_all to save multiple records and ensure they get their Version records created. Just a suggestion!

**Comment by narrowtux** [comment]
Hi @INGCRENGIFO,

sorry for not responding earlier. I've been procrastinating reviewing your PR, because, while using the returning option to get the final structs is quite clever, I'm not sure it covers every way you can use insert_all. 

If you need to use your feature in your app, you can change your dependency to ex_audit in your mix.exs like this:

`{:ex_audit, github: "INGCRENGIFO/ex_audit", ref: "master"}` until your PR is merged.

**Comment by INGCRENGIFO** [comment]
yes i'm using it that way. I just hope and can be of help in your repository, so that more people can access this useful functionality.

**Comment by ingcrengifo** [comment]
@narrowtux yes i'm using it that way. I just hope and can be of help in your repository, so that more people can access this useful functionality.
