### ISSUE TITLE
Version 0.7 on hex.pm does not contain the same code as described in github

### ISSUE THREAD

**Issue by m0rt3n** [ZennerIoT/ex_audit#57]
Hi!

The code I get from hex.pm does not contain the changes to ExAudit.Repo as here on github.
All the docs and code here on github refers to version 0.7, but that is clearly not available when code is fetched from hex.pm

I am using `{:ex_audit, "~> 0.7"}` in my mix.exs file.

First 10 lines of code in the code I got from hex.pm for ExAudit.Repo:

```
defmodule ExAudit.Repo do
  @moduledoc """
  Replaces Ecto.Repo to be able to keep track of changes made to entities in the repo.
  Changes made with the following functions are tracked, other function calls must be manually tracked:
   * `insert`, `insert!`
   * `update`, `update!`
   * `delete`, `delete!`
  ### Shared options
  All normal Ecto.Repo options will work the same, however, there are additional options specific to ex_audit:
   * `:ex_audit_custom` - Keyword list of custom data that should be placed in new version entries. Entries in this
```

First 10 lines here on github:

```
defmodule ExAudit.Repo do
  @moduledoc """
  Adds ExAudit version tracking to your Ecto.Repo actions. The following functions are
  extended to detect if the given struct or changeset is in the list of :tracked_schemas
  given in :ex_audit config:
    insert: 2,
    update: 2,
    insert_or_update: 2,
    delete: 2,
```

**Comment by narrowtux** [comment]
This is simply because there is new code in this repository which hasn't been released yet. The version number in mix.exs has been left untouched since the last release.

If you look at the state of `repo.ex` at the time when the version line in `mix.exs` was changed to 0.7, you can see that it matches the code from hex.pm exactly: https://github.com/ZennerIoT/ex_audit/blob/90522f759181327a04f18e85de4267ae04836117/lib/repo/repo.ex

**Comment by m0rt3nlund** [comment]
Yes of course, I misunderstood! :) Great library!
