### ISSUE TITLE
Callback Repo.reload missing

### ISSUE THREAD

**Issue by h4cc** [ZennerIoT/ex_audit#60]
The Repo.reload and Repo.reload! callbacks seem to miss:

https://hexdocs.pm/ecto/Ecto.Repo.html#c:reload/2

**Comment by narrowtux** [comment]
Not sure why these should need to be implemented, ex_audit's repo use macro only overrides a handful of functions from the original ecto repo, so all newly added repo functions should be available.

Since we do this when we build a repo:
```elixir
defmodule MyApp.Repo

  use Ecto.Repo, otp_app: :my_app
  use ExAudit.Repo, ...
end
```

Functions not overridden by `use ExAudit.Repo` "fall through" into the final `MyApp.Repo` module.

**Comment by rauann** [comment]
Actually, ex_audit needs to support ecto 3.5 to be able to use `Repo.reload/2` - https://github.com/ZennerIoT/ex_audit/pull/61
