### ISSUE TITLE
About maintaining this library.

### ISSUE THREAD

**Issue by revati** [ZennerIoT/ex_audit#91]
Hello, i know this is oss and i'm very glad about you made this library. Its has been handy for me. I truly grateful that you have done the work and created it. But i see that there are some maintenance latency.

Few PR have been idle for long time. Its an issue thats needs fixing (IMHO). Currently there are few PRs that have been merged in other forks:
- https://github.com/super-seguros/ex_audit
- https://github.com/LeadSimple/ex_audit

This creates divergence, as one has some PRs, other have different PRs. With time each one will diverge more and more. While all forks and main library will work on base level, at some point one will have features z,x,c and other will have x,c,v creating case where no library have z and v features together.

As a developer how can i know which one is the main library? I will require thorough research from user pow. 

My question is: are you willing to add some other developer as maintainers? That could go through/merge/create releases PRs for this library? If you are willing i'm would like to step forth and try my best to help you.

Im i no way trying to disrespect you. As it is free software you don't have any obligation to maintain it more than you are doing it currently. If thats the case, i personally would appreciate open communication about it. And then i most likely would try my best to create feature full fork. And try to maintain separately, but i rather collaborate. 

Either case, have a great day 👍🏼

**Comment by narrowtux** [comment]
Hello. I consider this library feature-complete and would only update it when there are breaking changes in ecto or elixir. We are still using it in our in-production app, so we'd notice if something breaks. 

I appreciate all the opened issues with feature ideas and merge requests, but I'm sadly not motivated to extend this library beyond its current scope, since we do not have internal needs for additional features and do not want to maintain new features we wouldn't use.
